### ISSUE TITLE
Add Duration.plus and Duration.minus

### ISSUE THREAD

**Issue by MartinSStewart** [ianmackenzie/elm-units#47]
It would be nice to have `Duration.plus : Duration -> Time.Posix -> Time.Posix` and `Duration.minus : Duration -> Time.Posix -> Time.Posix` included as they are fairly basic operations I usually end up needing.

There is a catch given that Time.Posix is an integer representing milliseconds. As a result, adding `Duration.miliseconds 0.1` to a `Time.Posix` wouldn't have any affect. While this is a bit unintuitive, I think it's enough to make note of it in the function documentation.

**Comment by ianmackenzie** [comment]
Good point about the accuracy, but yeah I think just having a clear note in the docs is the right approach there.

Thinking a bit about naming...`plus` and `minus` as above break the pattern of "`Duration` is the last argument", and as a result look slightly weird in things like

```elm
now |> Duration.plus (Duration.hours 3)
```

What about perhaps:

```elm
Duration.addTo : Time -> Duration -> Time
Duration.subtractFrom : Time -> Duration -> Time
```

I think these read pretty well as both

```elm
Duration.addTo now (Duration.hours 3)
```

and

```elm
Duration.hours 3 |> Duration.addTo now
```

although it admittedly does seem a bit odd to have duration coming before time in a pipeline.

Another option (either instead of, or in addition to, the above) might be to have

```elm
Duration.sinceEpoch : Time -> Duration

-- document that this conversion is lossy
Duration.asPosixTime : Duration -> Time
```

which would allow you to do things like

```elm
now
    |> Duration.sinceEpoch
    |> Quantity.plus (Duration.hours 3)
    |> Duration.asPosixTime
```

More verbose, but lets you construct pipelines starting with `Time` values while maintaining 'normal' argument order in `Duration` functions.

Thoughts? Could very well be that I'm overthinking this and your original suggestion is the best one 🙂

**Comment by MartinSStewart** [comment]
So far my placeholder functions have been in the form of `Duration -> Time.Posix -> Time.Posix` but now when I'm checking it's usages, there doesn't seem to be much reason it couldn't have been `Time.Posix -> Duration -> Time.Posix`. The latter seems make more sense, since then you can minimize precision loss by writing something like `timeOffset0 |> Quantity.minus timeOffset1 |> Duration.addTo now` instead of `now |> Duration.addTo timeOffset0 |> Duration.subtractFrom timeOffset1`.

I think `Duration.sinceEpoch` and `Duration.asPosixTime` should be held off on though. I personally don't think I'd need them and my gut feeling is that it's a bad idea to be using Duration to represent a point in time.

**Comment by ianmackenzie** [comment]
Good point about the precision! Seems like `addTo` and `subtractFrom` are probably the way to go for now. And yeah, I agree, if we can get away without `sinceEpoch`/`asPosixTime` etc. that would be great.
