### ISSUE TITLE
map function

### ISSUE THREAD

**Issue by dullbananas** [ianmackenzie/elm-units#48]
It would be defined like this:

```elm
map : ( number -> number ) -> Quantity number units -> Quantity number units
```

**Comment by ianmackenzie** [comment]
👋 @dullbananas!

I think I might even define it as

```elm
map : (number1 -> number2) -> Quantity number1 units1 -> Quantity number2 units2
```

which would allow things like `Quantity.map round` or `Quantity.map toFloat` that convert between different number types, or even things like `Quantity.map ((*) pi)` to [convert from hemispherical luminance to total illuminance](https://en.wikipedia.org/wiki/Luminance#Relation_to_Illuminance), which changes the quantity type from luminance (in nits) to illuminance (in lux).

The reason I haven't added `map` yet (or `map2`, `map3` etc.) is because they lose some type safety without that necessarily being obvious - there's nothing stopping you from providing a mathematical expression that doesn't match up with the declared units. You can already do 'unsafe' math by [unwrapping `Quantity` values manually](https://github.com/ianmackenzie/elm-units#custom-functions), but at least there I think it's more clear that you're doing something potentially unsafe and need to be careful. So my initial thinking was to leave out `map*` functions and see if it works out to write custom functions (as described in the previous link) that explicitly unwrap `Quantity` values instead.

Thoughts? Can you tell me a bit more about the use case you have/are considering?
